<?php
function uuidv4() {
    $data = random_bytes(16);
    $data[6] = chr(ord($data[6]) & 0x0f | 0x40); // set version to 0100
    $data[8] = chr(ord($data[8]) & 0x3f | 0x80); // set bits 6-7 to 10
    return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
}

$prodi_ti = uuidv4();
$prodi_si = uuidv4();

$kelas_ti = uuidv4();
$kelas_si = uuidv4();

$user_admin = uuidv4();
$user_dosen = uuidv4();
$user_mhs = uuidv4();

$dosen1 = uuidv4();
$mhs1 = uuidv4();

$matkul1 = uuidv4();
$matkul2 = uuidv4();
$matkul3 = uuidv4();

$periode1 = uuidv4();

$pass_admin = password_hash('admin123', PASSWORD_BCRYPT);
$pass_dosen = password_hash('dosen123', PASSWORD_BCRYPT);
$pass_mhs = password_hash('mhs123', PASSWORD_BCRYPT);

echo "/* SEED DATA GENERATED BY generate_uuid_seed.php */\n\n";
echo "INSERT INTO prodi (id_prodi, kode_prodi, nama_prodi) VALUES \n";
echo "('$prodi_ti', 'TI', 'Teknik Informatika'),\n";
echo "('$prodi_si', 'SI', 'Sistem Informasi');\n\n";

echo "INSERT INTO kelas (id_kelas, id_prodi, nama_kelas) VALUES \n";
echo "('$kelas_ti', '$prodi_ti', 'TI-A'),\n";
echo "('$kelas_si', '$prodi_si', 'SI-A');\n\n";

echo "INSERT INTO users (id_user, username, password_hash, nama_lengkap, role, status) VALUES \n";
echo "('$user_admin', 'admin', '$pass_admin', 'Administrator', 'admin', 'aktif'),\n";
echo "('$user_dosen', '1234567890', '$pass_dosen', 'Budi Dosen', 'dosen', 'aktif'),\n";
echo "('$user_mhs', '20260001', '$pass_mhs', 'Andi Mahasiswa', 'mahasiswa', 'aktif');\n\n";

echo "INSERT INTO dosen (id_dosen, id_user, nip, jk, email, id_prodi, profil_lengkap) VALUES \n";
echo "('$dosen1', '$user_dosen', '1234567890', 'L', 'budi@kampus.ac.id', '$prodi_ti', 1);\n\n";

echo "INSERT INTO mahasiswa (id_mahasiswa, id_user, npm, jk, email, angkatan, id_prodi, id_kelas, semester, status_akademik, profil_lengkap) VALUES \n";
echo "('$mhs1', '$user_mhs', '20260001', 'L', 'andi@kampus.ac.id', '2026', '$prodi_ti', '$kelas_ti', 1, 'aktif', 1);\n\n";

echo "INSERT INTO mata_kuliah (id_matkul, id_prodi, kode_matkul, nama_matkul, sks) VALUES \n";
echo "('$matkul1', '$prodi_ti', 'MK001', 'Algoritma', 3),\n";
echo "('$matkul2', '$prodi_ti', 'MK002', 'Basis Data', 3),\n";
echo "('$matkul3', '$prodi_si', 'MK003', 'Sistem Informasi Manajemen', 3);\n\n";

echo "INSERT INTO periode_akademik (id_periode, nama_periode, jenis_semester, tanggal_mulai, tanggal_selesai, status) VALUES \n";
echo "('$periode1', '2026/2027', 'Ganjil', '2026-08-01', '2027-01-31', 'aktif');\n\n";

echo "INSERT INTO bobot_nilai (nilai_huruf, bobot) VALUES \n";
echo "('A', 4.00), ('A-', 3.70), ('B+', 3.30), ('B', 3.00), ('B-', 2.70), ('C+', 2.30), ('C', 2.00), ('C-', 1.70), ('D', 1.00);\n\n";

echo "INSERT INTO pengaturan (`key`, `value`) VALUES \n";
echo "('biaya_kuliah_default', '1600000');\n\n";
